name: Build and deploy my-express-api

on:
  push:
    branches:
      - app/chatting

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the API
      run: npm run build:azure

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: strive-tribe   # Replace this!
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./dist/apps/my-express-api